### ISSUE TITLE
Партицирование в PostgreSQL

### ISSUE THREAD

**Issue by KseniiaKarpova** [KseniiaKarpova/Auth_sprint_2#5]
**Задание**
Партицируйте таблицу с пользователями. Подумайте, по каким критериям вы бы разделили её. Важно посмотреть на таблицу не только в текущем времени, но и заглядывая в некое будущее, когда в ней будут миллионы записей. Пользователи могут быть из одной страны, но из разных регионов. А ещё пользователи могут использовать разные устройства для входа и иметь разные возрастные ограничения.

**Comment by BigDeepBlue** [comment]
![Снимок экрана 2024-02-08 в 23 22 52](https://github.com/KseniiaKarpova/Auth_sprint_2/assets/73478414/b135fd4b-417f-498e-aedf-f8d44df892ae)
Оно и ругается, что ключ партицирования, должен быть включен в **PRIMARY KEY constraint** 
Вот как это сделано в моем примере
